"use client";

import React from "react";
import Link from "next/link";

export interface LabReport {
  id: string | number;
  reportNumber?: string;
  reportName?: string;
  reportType?: string;
  patientId?: string | number;
  patientName?: string;
  generatedBy?: string;
  generatedAt?: string;
  status?: string;
  recordCount?: number;
  fileType?: string;
  fileUrl?: string;
}

interface ReportTableProps {
  reports: LabReport[];
  loading?: boolean;
  onDelete?: (report: LabReport) => void;
  onDownload?: (report: LabReport) => void;
}

function formatDate(date?: string) {
  if (!date) return "—";

  const parsed = new Date(date);

  if (Number.isNaN(parsed.getTime())) {
    return date;
  }

  return parsed.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function statusClass(status?: string) {
  const value = status?.toLowerCase();

  if (
    value === "completed" ||
    value === "generated" ||
    value === "ready"
  ) {
    return "bg-green-50 text-green-700";
  }

  if (
    value === "failed" ||
    value === "error" ||
    value === "cancelled"
  ) {
    return "bg-red-50 text-red-700";
  }

  if (
    value === "pending" ||
    value === "processing"
  ) {
    return "bg-yellow-50 text-yellow-700";
  }

  return "bg-gray-100 text-gray-600";
}

function LoadingRows() {
  return (
    <>
      {Array.from({ length: 6 }).map((_, row) => (
        <tr key={row}>
          {Array.from({ length: 7 }).map((__, cell) => (
            <td key={cell} className="px-4 py-4">
              <div className="h-4 w-24 animate-pulse rounded bg-gray-200" />
            </td>
          ))}
        </tr>
      ))}
    </>
  );
}

export default function ReportTable({
  reports,
  loading = false,
  onDelete,
  onDownload,
}: ReportTableProps) {
  return (
    <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                Report
              </th>

              <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                Patient
              </th>

              <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                Type
              </th>

              <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                Generated By
              </th>

              <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                Generated
              </th>

              <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">
                Status
              </th>

              <th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wide text-gray-500">
                Actions
              </th>
            </tr>
          </thead>

          <tbody className="divide-y divide-gray-100">
            {loading ? (
              <LoadingRows />
            ) : reports.length === 0 ? (
              <tr>
                <td
                  colSpan={7}
                  className="px-6 py-16 text-center"
                >
                  <div className="text-3xl">📊</div>

                  <p className="mt-2 text-sm font-semibold text-gray-900">
                    No reports found
                  </p>

                  <p className="mt-1 text-sm text-gray-500">
                    Generated laboratory reports will
                    appear here.
                  </p>
                </td>
              </tr>
            ) : (
              reports.map((report) => (
                <tr
                  key={report.id}
                  className="hover:bg-gray-50"
                >
                  <td className="px-4 py-4">
                    <Link
                      href={`/reports/${report.id}`}
                      className="text-sm font-semibold text-gray-900 hover:underline"
                    >
                      {report.reportNumber ||
                        `RPT-${report.id}`}
                    </Link>

                    <p className="mt-1 text-xs text-gray-500">
                      {report.reportName ||
                        "Laboratory Report"}
                    </p>
                  </td>

                  <td className="px-4 py-4">
                    {report.patientId ? (
                      <Link
                        href={`/patients/${report.patientId}`}
                        className="text-sm font-medium text-gray-800 hover:underline"
                      >
                        {report.patientName ||
                          `Patient #${report.patientId}`}
                      </Link>
                    ) : (
                      <span className="text-sm text-gray-600">
                        {report.patientName || "—"}
                      </span>
                    )}
                  </td>

                  <td className="px-4 py-4">
                    <span className="text-sm text-gray-700">
                      {report.reportType || "General"}
                    </span>

                    {report.fileType && (
                      <p className="mt-1 text-xs uppercase text-gray-400">
                        {report.fileType}
                      </p>
                    )}
                  </td>

                  <td className="px-4 py-4 text-sm text-gray-700">
                    {report.generatedBy || "—"}
                  </td>

                  <td className="px-4 py-4 text-sm text-gray-600">
                    {formatDate(report.generatedAt)}
                  </td>

                  <td className="px-4 py-4">
                    <span
                      className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusClass(
                        report.status
                      )}`}
                    >
                      {report.status || "Pending"}
                    </span>
                  </td>

                  <td className="px-4 py-4">
                    <div className="flex justify-end gap-2">
                      <Link
                        href={`/reports/${report.id}`}
                        className="rounded-md border border-gray-200 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50"
                      >
                        View
                      </Link>

                      {onDownload && (
                        <button
                          type="button"
                          onClick={() =>
                            onDownload(report)
                          }
                          className="rounded-md border border-gray-200 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50"
                        >
                          Download
                        </button>
                      )}

                      {onDelete && (
                        <button
                          type="button"
                          onClick={() =>
                            onDelete(report)
                          }
                          className="rounded-md border border-red-200 px-3 py-1.5 text-xs font-medium text-red-600 hover:bg-red-50"
                        >
                          Delete
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}