"use client";

import React from "react";
import Link from "next/link";
import type { LabReport } from "./ReportTable";

interface ReportCardProps {
  report: LabReport;
  onDelete?: (report: LabReport) => void;
  onDownload?: (report: LabReport) => void;
}

function formatDate(date?: string) {
  if (!date) return "—";

  const parsed = new Date(date);

  if (Number.isNaN(parsed.getTime())) {
    return date;
  }

  return parsed.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function statusClass(status?: string) {
  const value = status?.toLowerCase();

  if (
    value === "completed" ||
    value === "generated" ||
    value === "ready"
  ) {
    return "bg-green-50 text-green-700";
  }

  if (
    value === "failed" ||
    value === "error" ||
    value === "cancelled"
  ) {
    return "bg-red-50 text-red-700";
  }

  if (
    value === "pending" ||
    value === "processing"
  ) {
    return "bg-yellow-50 text-yellow-700";
  }

  return "bg-gray-100 text-gray-600";
}

export default function ReportCard({
  report,
  onDelete,
  onDownload,
}: ReportCardProps) {
  return (
    <article className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm transition hover:shadow-md">
      <div className="flex items-start justify-between gap-3">
        <div className="flex min-w-0 items-center gap-3">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-gray-100 text-lg">
            📊
          </div>

          <div className="min-w-0">
            <Link
              href={`/reports/${report.id}`}
              className="block truncate text-base font-semibold text-gray-900 hover:underline"
            >
              {report.reportNumber ||
                `RPT-${report.id}`}
            </Link>

            <p className="mt-1 truncate text-xs text-gray-500">
              {report.reportName ||
                "Laboratory Report"}
            </p>
          </div>
        </div>

        <span
          className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-medium ${statusClass(
            report.status
          )}`}
        >
          {report.status || "Pending"}
        </span>
      </div>

      <div className="mt-5 space-y-4">
        <div>
          <p className="text-xs text-gray-400">
            Patient
          </p>

          {report.patientId ? (
            <Link
              href={`/patients/${report.patientId}`}
              className="mt-1 block text-sm font-semibold text-gray-800 hover:underline"
            >
              {report.patientName ||
                `Patient #${report.patientId}`}
            </Link>
          ) : (
            <p className="mt-1 text-sm font-semibold text-gray-800">
              {report.patientName || "—"}
            </p>
          )}
        </div>

        <div className="grid grid-cols-2 gap-4 rounded-lg bg-gray-50 p-4">
          <div>
            <p className="text-xs text-gray-400">
              Report Type
            </p>

            <p className="mt-1 text-sm font-medium text-gray-800">
              {report.reportType || "General"}
            </p>
          </div>

          <div>
            <p className="text-xs text-gray-400">
              Records
            </p>

            <p className="mt-1 text-sm font-medium text-gray-800">
              {typeof report.recordCount ===
              "number"
                ? report.recordCount
                : "—"}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <p className="text-xs text-gray-400">
              Generated By
            </p>

            <p className="mt-1 text-sm text-gray-700">
              {report.generatedBy || "—"}
            </p>
          </div>

          <div>
            <p className="text-xs text-gray-400">
              Generated
            </p>

            <p className="mt-1 text-sm text-gray-700">
              {formatDate(report.generatedAt)}
            </p>
          </div>
        </div>

        {report.fileType && (
          <div>
            <p className="text-xs text-gray-400">
              File Format
            </p>

            <p className="mt-1 text-sm font-medium uppercase text-gray-700">
              {report.fileType}
            </p>
          </div>
        )}
      </div>

      <div className="mt-5 flex justify-end gap-2 border-t border-gray-100 pt-4">
        <Link
          href={`/reports/${report.id}`}
          className="rounded-lg border border-gray-200 px-3 py-2 text-xs font-medium text-gray-700 hover:bg-gray-50"
        >
          View
        </Link>

        {onDownload && (
          <button
            type="button"
            onClick={() => onDownload(report)}
            className="rounded-lg border border-gray-200 px-3 py-2 text-xs font-medium text-gray-700 hover:bg-gray-50"
          >
            Download
          </button>
        )}

        {onDelete && (
          <button
            type="button"
            onClick={() => onDelete(report)}
            className="rounded-lg border border-red-200 px-3 py-2 text-xs font-medium text-red-600 hover:bg-red-50"
          >
            Delete
          </button>
        )}
      </div>
    </article>
  );
}