"use client";

import React, { useState } from "react";
import SettingsSection from "./SettingsSection";
import SettingsField from "./SettingsField";

export interface NotificationSettingsData {
  emailEnabled: boolean;
  smsEnabled: boolean;
  inAppEnabled: boolean;
  resultReady: boolean;
  resultApproved: boolean;
  criticalResult: boolean;
  paymentReceived: boolean;
  invoiceGenerated: boolean;
  analyzerOffline: boolean;
  analyzerError: boolean;
  failedLogin: boolean;
  reportGenerated: boolean;
  recipientEmail: string;
  senderName: string;
}

interface NotificationSettingsProps {
  initialValues?: Partial<NotificationSettingsData>;
  saving?: boolean;
  onSave?: (values: NotificationSettingsData) => void;
}

const defaults: NotificationSettingsData = {
  emailEnabled: true,
  smsEnabled: false,
  inAppEnabled: true,
  resultReady: true,
  resultApproved: true,
  criticalResult: true,
  paymentReceived: true,
  invoiceGenerated: true,
  analyzerOffline: true,
  analyzerError: true,
  failedLogin: true,
  reportGenerated: true,
  recipientEmail: "",
  senderName: "LabCore ELIS",
};

export default function NotificationSettings({
  initialValues,
  saving = false,
  onSave,
}: NotificationSettingsProps) {
  const [values, setValues] =
    useState<NotificationSettingsData>({
      ...defaults,
      ...initialValues,
    });

  const [saved, setSaved] = useState(false);

  const update = <
    K extends keyof NotificationSettingsData
  >(
    field: K,
    value: NotificationSettingsData[K]
  ) => {
    setValues((current) => ({
      ...current,
      [field]: value,
    }));

    setSaved(false);
  };

  const handleSave = () => {
    onSave?.(values);

    if (!onSave) {
      setSaved(true);
    }
  };

  const Toggle = ({
    label,
    description,
    field,
  }: {
    label: string;
    description: string;
    field: keyof NotificationSettingsData;
  }) => {
    const enabled = Boolean(values[field]);

    return (
      <div className="flex items-start justify-between gap-5 rounded-lg border border-gray-200 p-4">
        <div>
          <p className="text-sm font-semibold text-gray-800">
            {label}
          </p>

          <p className="mt-1 text-xs leading-5 text-gray-500">
            {description}
          </p>
        </div>

        <button
          type="button"
          onClick={() =>
            update(
              field,
              !enabled as NotificationSettingsData[typeof field]
            )
          }
          className={`relative mt-0.5 h-6 w-11 shrink-0 rounded-full transition ${
            enabled
              ? "bg-gray-900"
              : "bg-gray-300"
          }`}
          aria-label={`Toggle ${label}`}
        >
          <span
            className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${
              enabled ? "left-6" : "left-1"
            }`}
          />
        </button>
      </div>
    );
  };

  return (
    <div className="space-y-6">
      <SettingsSection
        title="Notification Channels"
        description="Choose which channels LabCore can use for notifications."
      >
        <div className="space-y-3">
          <Toggle
            label="Email Notifications"
            description="Send system notifications through email."
            field="emailEnabled"
          />

          <Toggle
            label="SMS Notifications"
            description="Send important alerts through SMS when configured."
            field="smsEnabled"
          />

          <Toggle
            label="In-app Notifications"
            description="Display alerts and activity notifications inside LabCore."
            field="inAppEnabled"
          />
        </div>
      </SettingsSection>

      <SettingsSection
        title="Laboratory Notifications"
        description="Configure notifications generated by laboratory workflows."
      >
        <div className="grid gap-3 md:grid-cols-2">
          <Toggle
            label="Result Ready"
            description="Notify when test results are ready for review."
            field="resultReady"
          />

          <Toggle
            label="Result Approved"
            description="Notify when a result has been approved."
            field="resultApproved"
          />

          <Toggle
            label="Critical Result"
            description="Notify authorized staff when a critical result is detected."
            field="criticalResult"
          />

          <Toggle
            label="Report Generated"
            description="Notify when a final laboratory report is generated."
            field="reportGenerated"
          />
        </div>
      </SettingsSection>

      <SettingsSection
        title="Billing Notifications"
        description="Configure payment and invoice notifications."
      >
        <div className="grid gap-3 md:grid-cols-2">
          <Toggle
            label="Payment Received"
            description="Notify when a patient payment is recorded."
            field="paymentReceived"
          />

          <Toggle
            label="Invoice Generated"
            description="Notify when a new invoice is generated."
            field="invoiceGenerated"
          />
        </div>
      </SettingsSection>

      <SettingsSection
        title="Analyzer & Security Alerts"
        description="Important operational and security notifications."
      >
        <div className="grid gap-3 md:grid-cols-2">
          <Toggle
            label="Analyzer Offline"
            description="Notify staff when an analyzer loses connectivity."
            field="analyzerOffline"
          />

          <Toggle
            label="Analyzer Error"
            description="Notify staff when an analyzer reports an error."
            field="analyzerError"
          />

          <Toggle
            label="Failed Login"
            description="Notify administrators about failed authentication attempts."
            field="failedLogin"
          />
        </div>
      </SettingsSection>

      <SettingsSection
        title="Email Configuration"
        description="Default sender and recipient configuration."
      >
        <div className="grid gap-5 md:grid-cols-2">
          <SettingsField
            label="Notification Recipient"
            description="Default email address for administrative notifications."
          >
            <input
              type="email"
              value={values.recipientEmail}
              onChange={(e) =>
                update(
                  "recipientEmail",
                  e.target.value
                )
              }
              placeholder="admin@example.com"
              className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm outline-none focus:border-gray-500 focus:ring-2 focus:ring-gray-100"
            />
          </SettingsField>

          <SettingsField label="Sender Name">
            <input
              type="text"
              value={values.senderName}
              onChange={(e) =>
                update(
                  "senderName",
                  e.target.value
                )
              }
              placeholder="LabCore ELIS"
              className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm outline-none focus:border-gray-500 focus:ring-2 focus:ring-gray-100"
            />
          </SettingsField>
        </div>
      </SettingsSection>

      <div className="flex flex-wrap items-center justify-end gap-3 rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
        {saved && (
          <p className="mr-auto text-sm font-medium text-green-600">
            ✓ Notification settings saved successfully
          </p>
        )}

        <button
          type="button"
          onClick={handleSave}
          disabled={saving}
          className="rounded-lg bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white hover:bg-gray-800 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {saving
            ? "Saving..."
            : "Save Notification Settings"}
        </button>
      </div>
    </div>
  );
}